### ISSUE TITLE
Disable exit prompt

### ISSUE THREAD

**Issue by Nowaker** [filiparag/wikiman#12]
Pressing `q` results in `Do you want to exit w3m? (y/n)`. This is not a default behavior of `man`, `less`, and other common CLI tools. I suggest disabling the exit prompt for Wikiman too.

**Comment by khuei** [comment]
> Pressing `q` results in `Do you want to exit w3m? (y/n)`. This is not a default behavior of `man`, `less`, and other common CLI tools.

This is the default behavior of `w3m`

**Comment by filiparag** [comment]
As @Z5483 pointed out, this is part of w3m, so Wikiman can't control it. In manual for `w3m` there doesn't seem to be a flag which would disable it.

If you need `q` to quit, change `tui_html` in your config file to another browser.
