### ISSUE TITLE
Allow ^C to exit in article view

### ISSUE THREAD

**Issue by Nowaker** [filiparag/wikiman#13]
In search results, `^C` is how you quit. `q` key acts as a filter, which is understandable.

In article view, `q` is how you quit. `^C` does nothing.

For consistency, `^C` in article view should quit.

**Comment by khuei** [comment]
> In article view, `q` is how you quit. `^C` does nothing.

This depends on which program `$MANPAGER` is set to.

> For consistency, `^C` in article view should quit.

In some programs, `^C` does not work, and `wikiman` cannot control that.
