### ISSUE TITLE
Incorporate Debian wiki

### ISSUE THREAD

**Issue by ethancedwards8** [filiparag/wikiman#16]
Put Debian Wiki into this, I may make a PR soon incorporating this.

**Comment by filiparag** [comment]
Creating a pull request for Debian Wiki would be great help.

**Comment by ethancedwards8** [comment]
Sure thing, but one thing. How did you find downloads for the FreeBSD and Gentoo wiki’s? I knew you can download Arch’s but I can’t seem to find Debian’s or Ubuntu’s.

**Comment by filiparag** [comment]
> How did you find downloads for the FreeBSD and Gentoo wiki’s?

There isn't an easy and universal way to do this. I created [build scripts](https://github.com/filiparag/wikiman/tree/master/build) for them which are kind of a hack, but work well enough. Downloading Gentoo Wiki was challenging because their web server rejects quick consecutive requests.

**Comment by filiparag** [comment]
Issue will be closed, but the discussion can continue.
