### ISSUE TITLE
Error with multiple sources in wikiman.conf

### ISSUE THREAD

**Issue by deuzene** [filiparag/wikiman#18]
I've got this error when I configure more than one source:

`sources = man, arch`

`error: source 'manarch' does not exist`

**Comment by filiparag** [comment]
Bug was introduced in [63d620d](https://github.com/filiparag/wikiman/tree/63d620d5009e057ffc0862173d48988144a1226e) and resolved in [f1e5545](https://github.com/filiparag/wikiman/tree/f1e5545ccc033b8775b1459fbf1838fdcface791).
