### ISSUE TITLE
*CAUTION* remove my $HOME/bin directory

### ISSUE THREAD

**Issue by ghost** [filiparag/wikiman#19]
The wikiman-makefile clean command just wiped out my $HOME/bin directory because i was stupid enough to run this without reading the source first. I probably should have done that plus ran it in a tmp directory, but live and learn. Luckily, I have tons of backups, so nothing was lost.

I'm not sure rm -rf bin is the best approach here, at the very least add a warning to the docs please.

**Comment by filiparag** [comment]
I am very sorry for causing you such trouble. I updated the [Makefile](https://github.com/filiparag/wikiman/blob/76008239d9773fb7fa438b85bcae3dcd160bc34d/Makefile) to only target its directory, so it shouldn't behave like that anymore.

If you have time, please leave me feedback for its further improvements, as I am relatively new to making and maintaining software packages.

**Comment by ghost** [comment]
Thank you for making the change quickly, I was more worried about someone without backups. I'll open some bug reports as I have time to go through it all.

**Comment by filiparag** [comment]
After further testing, even the new Makefile still causes problems on FreeBSD.

My development machine is running Arch Linux, so there I have the GNU variant, while on a testing machine I have FreeBSD 12.1. I am not well versed in non-GNU-exclusive features of the Makefile, so I RTFM as much as I can 🤷‍♂

Main problem i'm facing is how to get path of project's directory if you are making from outside its root. Currently it is using

```mk
WORKDIR:=$(shell dirname ${MAKEFILE_LIST})
```

which is not POSIX compliant. I would like not to have `gmake` as another dependency if there is a way to get this feature without it.

By the way, I made a [FreeBSD port](https://github.com/filiparag/wikiman#freebsd) in the meantime.

> I'll open some bug reports as I have time to go through it all.

@gregf Your help would be highly appreciated.

**Comment by ghost** [comment]
@filiparag About to sit down and have dinner, soon as I'm done I can help. There is also the option of depending on gmake in Freebsd.

**Comment by ghost** [comment]
@filiparag OK with some help I was able to sort it out. I just don't have any linux machines to test on, so I don't know if the same will work there. This worked for me in FreeBSD though.

WORKDIR != 	dirname Makefile

The follow link [here](http://www.khmere.com/freebsd_book/html/ch01.html) explains it.

>The bang equals sign "!=" is a shell command assignment. The value will be assigned the result of the command, after it is expanded and sent to the shell for execution. If the result has new lines they will be replaced with spaces.For example:
>
>VAR != < shell command to execute >

Should be enough to get you to where you need to be with some work? Hope that helps. If not let me know.

**Comment by filiparag** [comment]
Okay, so I made progress thanks to `!=`. Now I can get absolute path for Makefile's parent on FreeBSD:
```make
MKFILEREL!= echo ${.MAKE.MAKEFILES} | sed 's/.* //'
MKFILEABS!= readlink -f ${MKFILEREL}
WORKDIR!=   dirname ${MKFILEABS}
```
Of course, this doesn't work on GNU systems.

**EDIT:** Using this "hack" I was able to make it work on both systems:
```make
MKFILEREL!= echo ${.MAKE.MAKEFILES} | sed 's/.* //'
MKFILEABS!= readlink -f ${MKFILEREL} 2>/dev/null
MKFILEABS+= $(shell readlink -f ${MAKEFILE_LIST})
WORKDIR!= dirname ${MKFILEABS} 2>/dev/null
```
