### ISSUE TITLE
Support for Fedora

### ISSUE THREAD

**Issue by nmilosev** [filiparag/wikiman#2]
Hello, is it possible to add support for Fedora wiki? 😍♥️

**Comment by filiparag** [comment]
Arch Wiki was chosen as it also contains many articles for software unrelated to Arch Linux. If there is an easy way to download whole Fedora Wiki for offline use, it may be added as a optional source in the future versions.

**Comment by filiparag** [comment]
Support for additional sources is planned for a future release.
