### ISSUE TITLE
[Feature Request] Add shell completion scripts

### ISSUE THREAD

**Issue by khuei** [filiparag/wikiman#20]
This is not necessary, but I think it's nice to have.

**Comment by filiparag** [comment]
Yeah, I agree, that its a neat feature to have. 

I am currently focused on a FreeBSD port and package build automation, so it would be very helpful if you could start working on shell completion.

**Comment by khuei** [comment]
> it would be very helpful if you could start working on shell completion.

I will try to work on it, but I am currently having to deal with school/college issues; so it could take me awhile to start working on this.

**Comment by filiparag** [comment]
@Z5483 I added a [completions file](https://github.com/filiparag/wikiman/blob/master/completions/completions.fish) for fish shell. This is just an early version, so don't judge it too harshly.

This is not a priority for me, so your contribution would help a lot.

**Comment by khuei** [comment]
@filiparag I made a simple completion script for zsh/bash too. The only obstacle is the languages, since it's slightly different per source.

**Comment by filiparag** [comment]
I will close this issue, we can continue development discussion in a pull request.

**Comment by khuei** [comment]
It might be better to keep this open, so other people can see this too.

**Comment by filiparag** [comment]
You're right. Someone might see this and help with the development.

**Comment by filiparag** [comment]
I added `bash` completions and improved `fish` and `zsh` ones. Issue will be closed.
