### ISSUE TITLE
Fedora 32 error: unsupported installation path - failed to establish fallback

### ISSUE THREAD

**Issue by deuzene** [filiparag/wikiman#23]
Because Fedora links `/bin `to `/usr/bin` **wikiman** report this error (I don't know why). To fix this add:

```
/bin')
conf_sys_usr='/usr';
conf_sys_etc='/etc';;
```
to the `init()` function.

**Comment by filiparag** [comment]
Issue should be resolved in commit [3a0fd05](https://github.com/filiparag/wikiman/tree/3a0fd0582e0b6f32d7c8587dee0222b79c1f21cb).

Thanks for the report! and fix suggestion
