### ISSUE TITLE
Cannot search for zh-CN arch-wiki-docs

### ISSUE THREAD

**Issue by sainnhe** [filiparag/wikiman#28]
When I'm searching for zh-CN docs, it will report a warning:

```shell
$ wikiman -s arch -l zh-CN,en
warning: Arch Wiki for 'zhCN' does not exist
```

But that does exist in `/usr/share/doc/arch-wiki/html`

```shell
$ find '/usr/share/doc/arch-wiki/html' -maxdepth 1 -type d -printf '%P '
ro uk hr hu sv da es lt el zh-CN id he it sr pt zh-TW nb ko ca ru cs sk en bg eo pl ar fi tr th nl
```

**Comment by filiparag** [comment]
Thanks for opening this bug report. The issue occured in AWK script for locale autodetection, which allows you to write `zh` to use all available locales.

It should be fixed in [9b02431](https://github.com/filiparag/wikiman/commit/9b02431cf88de5145153b6d8645843696cb663da).
