### ISSUE TITLE
Can't load Handbook:AMD64/Installation/About.html

### ISSUE THREAD

**Issue by xezo360hye** [filiparag/wikiman#35]
If you try to follow links in Gentoo's Handbook, it'll show an error like in the title because there is no such file as `About.html`, instead there is a directory `About` with files in different languages (which I also can't access using links?). I don't know if this problem is Gentoo-wiki-specific, but it's kinda annoying that I can't view related pages without reopening (or opening new instance of) Wikiman

**Comment by filiparag** [comment]
The [script](https://github.com/filiparag/wikiman/blob/master/build/gentoo.sh) for crawling Gentoo Wiki is a bit _iffy_, as there isn't an official way to download the whole thng for viewing offline. That is also the reason why it is not updated as frequently as other Wikiman sources.

If you find a way to [fix links](https://github.com/filiparag/wikiman/blob/master/build/gentoo.sh#L31) better than it's done now, please submit a pull request. Right now, I don't have time to fix it myself. Sorry for your inconvenience,
