### ISSUE TITLE
Debian: /.config/wikiman/sources: No such file or directory

### ISSUE THREAD

**Issue by AngryPhantom** [filiparag/wikiman#8]
Hello,

I'm on Debian 10 and trying to use your utility.

```
username@domain:~$ wikiman 
find: ‘/home/username/.config/wikiman/sources’: No such file or directory
error: empty search query
```

Using the default config (`/etc/wikiman.conf`) which comes with the **.deb** package. No `~/.config/wikiman/` directory yet.

Isn't `man` the default source? Why it doesn't work then?

Thanks.

**Comment by AngryPhantom** [comment]
**UPDATE 1:**

After installing Arch Wiki sources via your instruction:

```
# Download latest Makefile
curl -L 'https://raw.githubusercontent.com/filiparag/wikiman/master/Makefile' -o 'wikiman-makefile'

# Example: install Arch Wiki
sudo make -f ./wikiman-makefile source-arch
```

And adding it to the config (`sources = man, arch`) the output is like this now:

```
username@domain:~$ wikiman 
error: empty search query
```

**Comment by AngryPhantom** [comment]
**UPDATE 2:**

Creating the `~/.config/wikiman/` directory with a local config doesn't fix this. After deleting this directory and editing `/etc/wikiman.conf` I'm getting the same error again:

```
username@domain:~$ wikiman 
find: ‘/home/username/.config/wikiman/sources’: No such file or directory
error: empty search query
```

**Comment by filiparag** [comment]
STDERR of `find` command for looking up source modules wasn't redirected into `/dev/null`, so if one or more of the directories were missing, it would display an error. I also [added a check](https://github.com/filiparag/wikiman/blob/3c9ae3b1cb7f3428e1a3b3027114860a9ec2eff7/wikiman.sh#L123-L126) to fail if no modules are found.

Issue should be resolved now. Please let me know if it persists!

**Comment by AngryPhantom** [comment]
@filiparag Yes, now it works as expected. Thank you! Cheers.

**Comment by AngryPhantom** [comment]
The only thing that would be nice is to get back to the Wikiman interface after reading any man. Is it possible? Because when I press q it just quits to the console.

**Comment by filiparag** [comment]
> The only thing that would be nice is to get back to the Wikiman interface after reading any man. Is it possible? Because when I press q it just quits to the console.

@AngryPhantom I added option to keep Wikiman open in [this commit](https://github.com/filiparag/wikiman/tree/3dda63280b7221f0db881950121920f26556a0c1). Now you can use `-k` flag or set `tui_keep_open = true` in your config file.

In the future, please open an individual issue for every bug report/feature request to keep things more organized.
